swagger: "2.0"
info:
  title: Products API overview
  version: v2
paths:
  /myretail/product/price:
    post:
      operationId: saveProductPrice
      summary: insert product price
      produces:
      - application/json
      responses:
        "200":
          description: |-
            200 400 response
          examples:
            application/json: |-
              {
                "currency_code": "USD",
                "product_id": "13860428",
                "value": "13.49"
              }
        "400":
          description: |-
            200 400 response
          examples:
            application/json: |-
              {
              }
  /myretail/product/price/{id}:
    get:
      operationId: getProductPrice
      summary: query product price
      produces:
      - application/json
      responses:
        "200":
          description: |-
            200 404 response
          examples:
            application/json: |-
              {
                "id": "13860428"
              }
        "404":
          description: |-
            200 404 response
          examples:
            application/json: |-
              {
                "id": "12345678"
              }
consumes:
- application/json